apiVersion: v1
kind: Pod
metadata:
  name: python-config-env
spec:
  containers:
  - name: app
    image: python:3.12-slim
    command: ["python","-c"]
    args:
      - |
        import os, time
        print("APP_MODE =", os.environ.get("APP_MODE"))
        print("GREETING =", os.environ.get("GREETING"))
        time.sleep(3600)
    envFrom:
    - configMapRef:
        name: app-config
